source 'https://github.com/nicksnyder/Specs.git'
use_frameworks!

target 'Charlie' do
  pod 'Alpha', :path => '../Alpha/'
  pod 'Bravo', :path => '../Bravo/'

  target 'CharlieTests' do
    inherit! :search_paths
  end

  target 'CharlieSampleApp' do
    inherit! :search_paths
  end
end
