source 'https://github.com/nicksnyder/Specs.git'
use_frameworks!

target 'Delta' do
  pod 'Alpha', :path => '../Alpha/'
  pod 'Bravo', :path => '../Bravo/'

  target 'DeltaTests' do
    inherit! :search_paths
  end
end
