source 'git@github.com:nicksnyder/Specs.git'
use_frameworks!

target 'SwiftApp' do
  pod 'Charlie', '~> 2.0'
  pod 'Delta', '~> 2.0'

  target 'SwiftAppTests' do
    inherit! :search_paths
  end

  target 'SwiftAppUITests' do
    inherit! :search_paths
  end
end
